### ISSUE TITLE
surface level filled with dirt?

### ISSUE THREAD

**Issue by fungreenfox** [andrepl/BuildInABox#23] opened 2013-06-11 16:52 UTC
When making a new schematic, i use the hoe.
Digging down to -12 sometimes below surfacelevel, and then the upper corner.
Saving the schematic fine. When spawning it, the basement is filled with dirt and can not be digged out.

**Comment by andrepl** [comment] 2013-06-11 16:54
The dirt can't be broken? That's definitely a bug.. the fact that it is there is normal (I'm working on that, but its hard to only ignore air above ground) but you should be able to dig it out, as it should only protect the blocks that are actually a part of the building.  I'll test this out tonight and see if I can find a fix.

**Comment by fungreenfox** [comment] 2013-06-11 16:56
![2013-06-11_18 57 48](https://f.cloud.github.com/assets/3235334/638270/2cc39d44-d2b8-11e2-85c5-95056b2209f5.png)
thanks. I was going to add, that i place the enderchest at the surface housecorner inside the claim. The basement seem to be there, at least about 4 blocks down but filled with dirt. Then i am blocked. 
I am currently blocking the house from being "griefed" or edited by config.

**Comment by andrepl** [comment] 2013-06-11 16:58
would it be possible for you to upload your schematic file and your plans.yml somewhere?  it's not critical but would help me debug the issue.

**Comment by fungreenfox** [comment] 2013-06-11 16:59
i can only paste them out i guess, not attaching.
i will put it at my domain mcraft.dk and post some links here

**Comment by fungreenfox** [comment] 2013-06-11 17:02
www.mcraft.dk/downloads/biab/blacksmith.schematic
www.mcraft.dk/downloads/biab/chests.yml
www.mcraft.dk/downloads/biab/config.yml
www.mcraft.dk/downloads/biab/plans.yml

**Comment by fungreenfox** [comment] 2013-06-11 17:21
i have some more screenshots, from testing. I made an area for the blacksmith, filled with item id 43 "double slap".
Only the surface got set with slaps but, Spawning the blacksmith, fills the basement with slaps too.
I removed the first layer entrance slaps with WE to see underneith.

![2013-06-11_19 21 52](https://f.cloud.github.com/assets/3235334/638411/750afb94-d2bb-11e2-9dac-25db46f32120.png)
![2013-06-11_19 18 16](https://f.cloud.github.com/assets/3235334/638404/48d9bd62-d2bb-11e2-9c15-e2f7b03e314e.png)

**Comment by fungreenfox** [comment] 2013-06-11 17:35
Next test spawning was up in the air. i have more than 5 shots of this.
It makes the basement now but fills basement entrance with the item from surface level, but only there. i could dig myself into the first door and hole basement is ok. But only when spawned in the air.
![2013-06-11_19 32 57](https://f.cloud.github.com/assets/3235334/638471/3d8cfda0-d2bd-11e2-81ae-2b5725286b94.png)
![2013-06-11_19 33 01](https://f.cloud.github.com/assets/3235334/638473/44139706-d2bd-11e2-940d-b6c45e0bfe2b.png)
![2013-06-11_19 32 32](https://f.cloud.github.com/assets/3235334/638490/991721f0-d2bd-11e2-88f9-67210960a07a.png)

**Comment by fungreenfox** [comment] 2013-06-12 13:17
Is it still possible to save selection done by WE instead?

**Comment by andrepl** [comment] 2013-06-12 15:14
not right now, I have considered keeping that functionality but its the ONLY reason I have to include WorldEdit in my build process, and It's nice not having to depend on their code, as it really sucks to work with.  I've been busy working out some bugs with a new Grief Prevention fork, so I haven't had time to look into this yet, but I will ASAP.

I was thinking today about the lag spike during preview... if its possible, would you be able to test it with `check-build-permissions: false`  the problem is that to test build permissions, i have to fire a BlockPlaceEvent for every single block in the schematic and then check if another plugin cancelled it, and I have to do all of this during the preview.  

The reason I did it this way is to avoid having to support every possible land-protection plugin out there.. but it's obviously got some heavy performance implications.  If the lag disappears when changing that setting, then I'll know what needs to be done :)

**Comment by fungreenfox** [comment] 2013-06-12 21:21
Sure i will test it. Its the least i can do for you. The users are soon gone for the day, and i can use the night to test with.

**Comment by fungreenfox** [comment] 2013-06-12 21:35
ah ok, i found it now in your config. i am testing now.

**Comment by fungreenfox** [comment] 2013-06-12 21:48
Currently when placing the blacksmith box, i get a preview fine and very fast, but not in those seconds i have set it to. 10 secs becomes 3-4 secs. and the box pops back to me in inventory.

**Comment by fungreenfox** [comment] 2013-06-12 21:48
oh wait, i did not have build permissions hehe. 
2nd edit: the box is popping back to me again, with biab config permission check false, and normal build permission true. - I get the message, that i can right click to accept the building, then it pops off.

**Comment by fungreenfox** [comment] 2013-06-12 21:55
with biab check build permissions true, i also get a mysql fault, wich i cannot repair for my main world. I am using phhpmyadmin, and normally i can repair any duplicate key in the tables but not this one. The phpmyadmin interface tells me that no error exists in the table(s). i get around 100 lines with dublicate key 1. 

---

23:53:17 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'delwinstown-2236-50-819' for key 1
23:53:17 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23:53:17 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
23:53:17 [SEVERE]       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
23:53:17 [SEVERE]       at java.lang.reflect.Constructor.newInstance(Unknown Source)
23:53:17 [SEVERE]       at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
23:53:17 [SEVERE]       at com.mysql.jdbc.Util.getInstance(Util.java:382)
23:53:17 [SEVERE]       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
23:53:17 [SEVERE]       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.sql.MySQL.updatePlacedBlockinSQL(MySQL.java:148)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.listeners.BlockPlaceListener.addBlock(BlockPlaceListener.java:61)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:54)
23:53:17 [SEVERE]       at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
23:53:17 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
23:53:17 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
23:53:17 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
23:53:17 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
23:53:17 [SEVERE]       at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
23:53:17 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
23:53:17 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildChest$2.processBlock(BuildChest.java:178)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildManager$BuildTask.tick(BuildManager.java:90)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildManager.run(BuildManager.java:41)
23:53:17 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
23:53:17 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
23:53:17 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'delwinstown-2235-50-820' for key 1
23:53:17 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23:53:17 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
23:53:17 [SEVERE]       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
23:53:17 [SEVERE]       at java.lang.reflect.Constructor.newInstance(Unknown Source)
23:53:17 [SEVERE]       at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
23:53:17 [SEVERE]       at com.mysql.jdbc.Util.getInstance(Util.java:382)
23:53:17 [SEVERE]       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
23:53:17 [SEVERE]       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.sql.MySQL.updatePlacedBlockinSQL(MySQL.java:148)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.listeners.BlockPlaceListener.addBlock(BlockPlaceListener.java:61)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:54)
23:53:17 [SEVERE]       at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
23:53:17 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
23:53:17 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
23:53:17 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
23:53:17 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
23:53:17 [SEVERE]       at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
23:53:17 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
23:53:17 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildChest$2.processBlock(BuildChest.java:178)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildManager$BuildTask.tick(BuildManager.java:90)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildManager.run(BuildManager.java:41)
23:53:17 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
23:53:17 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
23:53:17 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'delwinstown-2236-50-820' for key 1
23:53:17 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23:53:17 [SEVERE]       at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
23:53:17 [SEVERE]       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
23:53:17 [SEVERE]       at java.lang.reflect.Constructor.newInstance(Unknown Source)
23:53:17 [SEVERE]       at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
23:53:17 [SEVERE]       at com.mysql.jdbc.Util.getInstance(Util.java:382)
23:53:17 [SEVERE]       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
23:53:17 [SEVERE]       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
23:53:17 [SEVERE]       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
23:53:17 [SEVERE]       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.sql.MySQL.updatePlacedBlockinSQL(MySQL.java:148)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.listeners.BlockPlaceListener.addBlock(BlockPlaceListener.java:61)
23:53:17 [SEVERE]       at org.seed419.founddiamonds.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:54)
23:53:17 [SEVERE]       at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
23:53:17 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
23:53:17 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
23:53:17 [SEVERE]       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
23:53:17 [SEVERE]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
23:53:17 [SEVERE]       at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
23:53:17 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
23:53:17 [SEVERE]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildChest$2.processBlock(BuildChest.java:178)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildManager$BuildTask.tick(BuildManager.java:90)
23:53:17 [SEVERE]       at com.norcode.bukkit.buildinabox.BuildManager.run(BuildManager.java:41)
23:53:17 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
23:53:17 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
23:53:17 [SEVERE]       at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by fungreenfox** [comment] 2013-06-12 21:59
I went to another world and no duplicate key, but the box is still popping off after preview. I must have changed something else i guess.

Correction: I get some duplicate error for tables in console with my "owner" player, even in another world. The duplicate key is only showing up when launching the box. It still pops off. I have had these errors since starting using biab, but i wasnt sure whether it was my own servers fault or biab, so i did not mention it earlier.
Another issue is the box diapearing from inventory. But if relogging or changing world, its coming back to inv.
(don't worry, i'm not tired of testing, - its an interesting project)

**Comment by fungreenfox** [comment] 2013-06-13 00:02
Biab is not building the project after preview. I don't know what i have changed to make it abandon the building process. It is not about the claim or building rights in the group or world.

**Comment by andrepl** [comment] 2013-06-13 01:27
I just uploaded Build 135 to jenkins, it should fix the air-blocks below ground, but I haven't really tested it yet.  I have no idea what could be causing the new problem, is `check-build-permissions` still `false` ?

**Comment by fungreenfox** [comment] 2013-06-13 01:54
andrepl you may add me to skype, if this is becoming a to large thread. its "mafaeste".
I will start testing the build.

**Comment by fungreenfox** [comment] 2013-06-13 02:40
i have started over on scratch, with clean biab files, to make it work again.

I start 135 building strandvilla and it shows preview, and removing it saying "building strandvilla". then nothing happens ingame, just empty area, and console errors:
04:34:50 [INFO] Fungreenfox issued server command: /biab give strandvilla
04:35:42 [INFO] SeruBans has checked in with database
04:36:38 [INFO] [Buycraft] Package checker successfully executed.
04:38:29 [WARNING] [BuildInABox] Task #3080 for BuildInABox v0.2.1-SNAPSHOT generated an exception
java.lang.NullPointerException
        at com.norcode.bukkit.buildinabox.BuildChest$4.processBlock(BuildChest.java:334)
        at com.norcode.bukkit.buildinabox.BuildManager$BuildTask.tick(BuildManager.java:90)
        at com.norcode.bukkit.buildinabox.BuildManager.run(BuildManager.java:41)
        at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_5_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:513)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by fungreenfox** [comment] 2013-06-13 02:42
This was kinda expected at this building, i will now try the blacksmith when i have made a new schematic.

**Comment by fungreenfox** [comment] 2013-06-13 02:50
![2013-06-13_04 49 09](https://f.cloud.github.com/assets/3235334/646548/eb4b1938-d3d3-11e2-91aa-c6b3a1b393a4.png)
The blacksmith can build ok, and no errors in console at this schematic, but is still filled with grass in the basement.

www.mcraft.dk/downloads/biab/blacksmith.schematic
www.mcraft.dk/downloads/biab/strandvilla.schematic

**Comment by fungreenfox** [comment] 2013-06-13 02:59
All dirt in the basement was removeable without use of WE, except 6 blocks in the roof of the basement. 
Build protection set to true here, no changings possible for the user who spawned it.

**Comment by fungreenfox** [comment] 2013-06-13 03:10
I removed the dirt manually and started on folding the house down again. I noticed, that the entrance to the basement was filled again with dirt, from the doors entrance and inside. Wich should be a sign, that the capturing process of basement is recoqnized as dirt and not air.

**Comment by andrepl** [comment] 2013-06-13 03:15
that's expected, if the dirt was there once, it will always be.  the schematic is NEVER changed, only chest contents are saved uniquely.  

the mysql error is not a problem in your database, its your 'founddiamonds' plugin complaining about the fake blockbreak event that I am sending (with a null value apparently) that will be fixed when the first error is.

I'm going to try something else and have a new build soon

**Comment by fungreenfox** [comment] 2013-06-13 03:27
oh very nice discovered. 
bt. with building the blacksmith with build permissionscheck :false, the basement is still filled , but all dirt can be removed and the basement is build ok as the original is captured from. (basement is always build correct, but filled).
i noticed, when i entered next room in the basement, the center of the room was not filled, but the walls from top to bottom was.

**Comment by andrepl** [comment] 2013-06-13 03:47
136 should be on jenkins now.  basements are working perfectly for me now. My next goal is to remove the restriction of the enderchest having to be inside the clipboard, but that will probably be tomorrow :)

**Comment by fungreenfox** [comment] 2013-06-13 04:01
testing..

**Comment by fungreenfox** [comment] 2013-06-13 04:03
is it this one? http://mcgitlab.norcode.com:8081/job/BuildInABox/136/com.norcode.bukkit.buildinabox$BuildInABox/

**Comment by andrepl** [comment] 2013-06-13 04:07
yep

**Comment by fungreenfox** [comment] 2013-06-13 04:10
Has someone complained about the chest being inside selection? OK, i could live with that.

**Comment by andrepl** [comment] 2013-06-13 04:11
I have had a few confused by it at first, and it shouldn't be necessary anymore because I added the step to select the enderchest at the end of the save process.

**Comment by fungreenfox** [comment] 2013-06-13 04:11
i would like to see a message if the building is to large for being folded out again. It can always safe it, but needs testing before given out.

**Comment by fungreenfox** [comment] 2013-06-13 04:16
basement is perfect now :)

**Comment by andrepl** [comment] 2013-06-13 04:16
The only restriction on size is 32767x32767x32767, anything else will work fine as long as the server doesn't lag out :)

**Comment by fungreenfox** [comment] 2013-06-13 04:18
you know the WE command //expand 10 down , can you add this to your hoe, that we wont have to dig down, but just say we want 10 down?

**Comment by fungreenfox** [comment] 2013-06-13 04:20
well, i have 113 plugins according to the counter but i count only half of it.
the cpu is 3ghz octa core, 24GB ram. But there are limitations in size of houses smaller than you say there. Else it pops the box and kicks everyone, goes into no respond mode for minutes.

**Comment by andrepl** [comment] 2013-06-13 04:23
yeah that's the server lagging out.. theres nothing "wrong" exactly. its just stressing the server way beyond its capacity for a few minutes.  once I work out the block protection events it'll get much lighter. 

I will add some clipboard manipulating commands right now.

**Comment by fungreenfox** [comment] 2013-06-13 04:25
BTW. can you include a message for where we click the box to save the selection, that biab noticed the click?
At large selections it might be a wonder if anything is going on there.

**Comment by fungreenfox** [comment] 2013-06-13 04:28
i am trying to save a luxusvilla but when it says i shall hit the chest, nothing happens. I guess the building is to large.

**Comment by fungreenfox** [comment] 2013-06-13 04:29
it says "now choose a enderchest to save it in", and i click the chest once, but it now starts to just open the chest and nothing thereafter.

**Comment by fungreenfox** [comment] 2013-06-13 04:35
hmm it is the size of building that determins if it want to save.

**Comment by andrepl** [comment] 2013-06-13 04:42
is there an error message when that happens?  I can't think of any reason that would happen :\

anyway, I've uploaded another build which adds /biab expandselection  it's still a little bit rough, not much error checking, but it works pretty much like worldguard:

`/biab expandselection d 10` to go down 10

`/biab expandselection u 20` to go up 20

you can also use `down` or `up`  BUT `east`, `west`, `north`, `south` will have to wait til tomorrow ;)

**Comment by fungreenfox** [comment] 2013-06-13 04:48
very nice. ill play around with it till then :)

I checked the console, and found this
06:44:42 [SEVERE] Could not pass event PlayerInteractEvent to BuildInABox v0.2.1-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at org.bukkit.craftbukkit.v1_5_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:186)
        at net.minecraft.server.v1_5_R3.PlayerInteractManager.interact(PlayerInteractManager.java:370)
        at net.minecraft.server.v1_5_R3.PlayerConnection.a(PlayerConnection.java:631)
        at net.minecraft.server.v1_5_R3.Packet15Place.handle(SourceFile:58)
        at net.minecraft.server.v1_5_R3.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R3.PlayerConnection.d(PlayerConnection.java:109)
        at net.minecraft.server.v1_5_R3.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R3.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R3.MinecraftServer.r(MinecraftServer.java:581)
        at net.minecraft.server.v1_5_R3.DedicatedServer.r(DedicatedServer.java:226)
        at net.minecraft.server.v1_5_R3.MinecraftServer.q(MinecraftServer.java:477)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:410)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at com.norcode.bukkit.schematica.Clipboard.copyBlockFromWorld(Clipboard.java:481)
        at com.norcode.bukkit.schematica.Session.copy(Session.java:76)
        at com.norcode.bukkit.buildinabox.BuildingPlan.fromClipboard(BuildingPlan.java:117)
        at com.norcode.bukkit.buildinabox.listeners.PlayerListener.onPlayerSelection(PlayerListener.java:74)
        at sun.reflect.GeneratedMethodAccessor257.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 17 more

**Comment by andrepl** [comment] 2013-06-13 04:48
Im going to close this ticket now since its getting long, and the dirt in the basement is fixed.  I'll open a new one for the large schematic not working.

**Closed as completed** 2013-06-13 04:48 UTC
